package index

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetStartEndHandlerFunc turns a function with the right signature into a get start end handler
type GetStartEndHandlerFunc func(GetStartEndParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStartEndHandlerFunc) Handle(params GetStartEndParams) middleware.Responder {
	return fn(params)
}

// GetStartEndHandler interface for that can handle valid get start end params
type GetStartEndHandler interface {
	Handle(GetStartEndParams) middleware.Responder
}

// NewGetStartEnd creates a new http.Handler for the get start end operation
func NewGetStartEnd(ctx *middleware.Context, handler GetStartEndHandler) *GetStartEnd {
	return &GetStartEnd{Context: ctx, Handler: handler}
}

/*GetStartEnd swagger:route GET /{start}/{end} index getStartEnd

GetStartEnd get start end API

*/
type GetStartEnd struct {
	Context *middleware.Context
	Handler GetStartEndHandler
}

func (o *GetStartEnd) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetStartEndParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
