package models

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// NotReady not ready
// swagger:model not_ready
type NotReady struct {
}

// Validate validates this not ready
func (m *NotReady) Validate(formats strfmt.Registry) error {
	return nil
}
