package models

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Partial partial
// swagger:model partial
type Partial struct {
}

// Validate validates this partial
func (m *Partial) Validate(formats strfmt.Registry) error {
	return nil
}
