package models

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Ready ready
// swagger:model ready
type Ready struct {
}

// Validate validates this ready
func (m *Ready) Validate(formats strfmt.Registry) error {
	return nil
}
