package models

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Started started
// swagger:model started
type Started struct {
}

// Validate validates this started
func (m *Started) Validate(formats strfmt.Registry) error {
	return nil
}
